spring:
  fabric:
    chaincode:
      identify: land
      name: land
      version: 1.0
    channel: basechannel
    organizations:
      - org1
    name: xxzx-fabric
    gateway:
      wallet:
        caUrl: https://ca.org1.xxzx.com:7054
        caFile: peerConfig/ca.org1.xxzx.com-cert.pem
        cahost: ca.org1.xxzx.com
        caMsp: Org1MSP
        identity: org1admin
        identityPw: org1adminpw
        file: C:\Users\MSI\Desktop\spring-fabric-gateway-master\fabric-explorer-spring-boot-starter\wallet
        memory: true
    network:
      file: peerConfig\connection-org1.yaml
      name: fabric network name
    explorer:
      path: manager
      title: 通道信息管理
      copyright:
    channelConfig:
      httpConfigTxLator: http://192.168.17.132:7059
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.17.129:3306/fabric?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
server:
  connection-timeout: 180000
  tomcat:
    max-connections: 100000

mybatis-plus:
  #  datasource: dataSource
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  io.github.ecsoya.fabric.explorer.repository.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID", 4:"该类型为未设置主键类型", 5:"字符串全局唯一ID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型